=head1 FTN::JAM ToDo

Verify/ensure that variables passed to subroutines are unpacked to local
variables before being used in the subroutine.

Localize usage of Magic variable "$|".

Verify/ensure that booleans being used in the same code are of the same
precedence.

Move FTN::JAM::Subfields, FTN::JAM::Attr, and FTN::JAM::Errnum into their
own module files?

Create a file containing examples of using FTN::JAM, possibly using something
from the demo scripts as a basis.  Do this instead of simply cleaning up the
old demo scripts and including them in the distribution? Or do some or all
of both?  I.E.;  add an EXAMPLES section in FTN::JAM and/or a separate file
such as FTN::JAM::Examples, and have example scripts based on cleaned up demo
scripts?

Add test subroutines for createing and removing a message base:  for that,
need to figure out where to put temporary files used with/for/in testing.
Adapt some and/or all of the demo scripts as part of the testing?

=head1 SEE ALSO

 L<FTN::JAM>, L<FTN::JAM::Examples>

=head1 AUTHOR

Robert James Clay, C<< <jame at rocasa.us> >>

=head1 COPYRIGHT & LICENSE

Copyright 2011 Robert James Clay, all rights reserved.

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.

=cut


